export const usageConstants = {
    LIST_USAGE_REQUEST: 'LIST_USAGE_REQUEST',
    LIST_USAGE_SUCCESS: 'LIST_USAGE_SUCCESS',
    LIST_USAGE_FAILURE: 'LIST_USAGE_FAILURE',

    GET_USAGE_REQUEST: 'GET_USAGE_REQUEST',
    GET_USAGE_SUCCESS: 'GET_USAGE_SUCCESS',
    GET_USAGE_FAILURE: 'GET_USAGE_FAILURE',

    DELETE_USAGE_REQUEST: 'DELETE_USAGE_REQUEST',
    DELETE_USAGE_SUCCESS: 'DELETE_USAGE_SUCCESS',
    DELETE_USAGE_FAILURE: 'DELETE_USAGE_FAILURE',

    CREATE_USAGE_REQUEST: 'CREATE_USAGE_REQUEST',
    CREATE_USAGE_SUCCESS: 'CREATE_USAGE_SUCCESS',
    CREATE_USAGE_FAILURE: 'CREATE_USAGE_FAILURE',

    UPDATE_USAGE_REQUEST: 'UPDATE_USAGE_REQUEST',
    UPDATE_USAGE_SUCCESS: 'UPDATE_USAGE_SUCCESS',
    UPDATE_USAGE_FAILURE: 'UPDATE_USAGE_FAILURE',
};