export const usageTypeConstants = {
    LIST_USAGE_TYPE_REQUEST: 'LIST_USAGE_TYPE_REQUEST',
    LIST_USAGE_TYPE_SUCCESS: 'LIST_USAGE_TYPE_SUCCESS',
    LIST_USAGE_TYPE_FAILURE: 'LIST_USAGE_TYPE_FAILURE',

    GET_USAGE_TYPE_REQUEST: 'GET_USAGE_TYPE_REQUEST',
    GET_USAGE_TYPE_SUCCESS: 'GET_USAGE_TYPE_SUCCESS',
    GET_USAGE_TYPE_FAILURE: 'GET_USAGE_TYPE_FAILURE',

    DELETE_USAGE_TYPE_REQUEST: 'DELETE_USAGE_TYPE_REQUEST',
    DELETE_USAGE_TYPE_SUCCESS: 'DELETE_USAGE_TYPE_SUCCESS',
    DELETE_USAGE_TYPE_FAILURE: 'DELETE_USAGE_TYPE_FAILURE',

    CREATE_USAGE_TYPE_REQUEST: 'CREATE_USAGE_TYPE_REQUEST',
    CREATE_USAGE_TYPE_SUCCESS: 'CREATE_USAGE_TYPE_SUCCESS',
    CREATE_USAGE_TYPE_FAILURE: 'CREATE_USAGE_TYPE_FAILURE',

    UPDATE_USAGE_TYPE_REQUEST: 'UPDATE_USAGE_TYPE_REQUEST',
    UPDATE_USAGE_TYPE_SUCCESS: 'UPDATE_USAGE_TYPE_SUCCESS',
    UPDATE_USAGE_TYPE_FAILURE: 'UPDATE_USAGE_TYPE_FAILURE',
};